String timestamp() ;
void handleReboot();
void handleConfig();
void handleMode();
void handleHead();
void handleLed();
void handleStatus();
void handleRawStatus();
void handleEye();
void handleArm();
